config/deploy/staging.hcl

Add an hcl file that we can use to deploy with nomad

---

.circleci/config.yml
README.md
config/test.exs
lib/dpul_collections/application.ex
test/dpul_collections_web/controllers/error_html_test.exs
test/dpul_collections_web/controllers/error_json_test.exs

This caches, builds, and runs both tests and formatting.
Closes #38, closes #35

Add CircleCI Configuration

---

architecture-decisions/0002-indexing.md

Update ADR language for caches instead of logs

---

.github/workflows/clean-images.yml

Try automated container cleaning.

---

lib/dpul_collections/indexing_pipeline/figgy_hydrator.ex
lib/dpul_collections/indexing_pipeline/figgy_producer.ex
lib/dpul_collections/indexing_pipeline/processor_marker.ex
test/dpul_collections/indexing_pipeline/figgy_producer_test.exs
test/dpul_collections/indexing_pipeline/integration/figgy_hydrator_integration_test.exs
test/dpul_collections/indexing_pipeline/processor_marker_test.exs
test/support/figgy_test_producer.ex
test/support/test_consumer.ex

This also moves `marker()`, because it made the docs make more sense.

Add some docs.

---

config/deploy/staging.hcl

Uses node pools defined in https://github.com/pulibrary/princeton_ansible/pull/5292

Deploy DPULC to staging boxes only.

---

README.md
bin/console

This'll open a bash shell or elixir console into a running container.

Add console script.

---

.lando.yml
config/deploy/staging.hcl
config/dev.exs
config/runtime.exs
lib/dpul_collections/application.ex
lib/dpul_collections/indexing_pipeline/figgy/hydration_consumer.ex
lib/dpul_collections/indexing_pipeline/figgy/transformation_consumer.ex
solr/config/solrconfig.xml
test/dpul_collections/indexing_pipeline/figgy/hydration_consumer_test.exs
test/dpul_collections/indexing_pipeline/integration/figgy/transformation_integration_test.exs

- **Start making indexing work in dev**
- **Start up with phx.server, and commit.**
- **Revert "Move hydration cache writes out of batcher back to consumers"**
- **Move to persistence in the transformation consumer to handle_batch
- **Add figgy database config to runtime.exs
- **Add solr config to runtime.exs 
- **Added figgy database and solr url to staging.hcl

Make indexing run in staging and dev

---

config/config.exs
config/dev.exs
config/prod.exs
config/test.exs
lib/dpul_collections/application.ex

Work on getting dpulc to deploy.

Get DPUL-C to deploy to staging

---

config/deploy/staging.hcl
config/dev.exs
config/runtime.exs
lib/dpul_collections/application.ex
lib/dpul_collections/indexing_pipeline/figgy/hydration_consumer.ex
lib/dpul_collections/indexing_pipeline/figgy/indexing_consumer.ex
lib/dpul_collections/indexing_pipeline/figgy/transformation_consumer.ex
test/dpul_collections/indexing_pipeline/integration/figgy/hydration_integration_test.exs
test/dpul_collections/indexing_pipeline/integration/figgy/indexing_integration_test.exs
test/dpul_collections/indexing_pipeline/integration/figgy/transformation_integration_test.exs
test/dpul_collections/indexing_pipeline/integration/full_integration_test.exs
test/support/mock_figgy_hydration_producer.ex
test/support/mock_figgy_indexing_producer.ex
test/support/mock_figgy_transformation_producer.ex

Fix cache version in tests so it's not always 0.
Move cache version to a variable defined in hcl file

Fix cache version

---

lib/dpul_collections/indexing_pipeline/figgy/hydration_consumer.ex
test/dpul_collections/indexing_pipeline/integration/full_integration_test.exs

Fix missing DatabaseProducer reference

---

lib/dpul_collections/indexing_pipeline.ex
lib/dpul_collections/indexing_pipeline/figgy/hydration_cache_entry.ex
lib/dpul_collections/indexing_pipeline/figgy/transformation_consumer.ex
solr/config/schema.xml
test/dpul_collections/indexing_pipeline/figgy/hydration_cache_entry_test.exs
test/dpul_collections/indexing_pipeline/integration/full_integration_test.exs
test/support/fixtures/figgy_test_fixtures.ex

closes #134 
I made the display date single valued. Open to discussion here.
- Refactor transformation logic into entry module
- Small corrections to comments
- Add years_is to index
- Add display_date_ss
- Mix format
- Add assertions for date solr fields to integration test
- Make display date single value

Index dates

---

lib/dpul_collections/solr.ex
lib/dpul_collections_web/live/home_live.ex
lib/dpul_collections_web/live/search_live.ex
lib/dpul_collections_web/router.ex
test/dpul_collections/indexing_pipeline/integration/full_integration_test.exs
test/dpul_collections/solr_test.exs
test/dpul_collections_web/live/home_live_test.exs
test/dpul_collections_web/live/search_live_test.exs

Add search results LiveView

---

lib/dpul_collections/solr.ex
solr/config/solrconfig.xml

Move keyword search params to solr config

---

README.md

Document solr config synchronization in readme

---

bin/console

Fixes error "no cluster leader" -- prod1 is no longer in use but I guess is still around.

Connect to console on an active nomad host

---

lib/dpul_collections/indexing_pipeline.ex
test/dpul_collections/indexing_pipeline_test.exs

Filter Events and PreservationObjects

---

.github/ISSUE_TEMPLATE/issue_template.md

Just a small template to get us started; we can change or expand from here.
Came out of discussions at team retrospective.

Add an initial issue template

---

lib/dpul_collections_web/components/lux-components.ex

Update applicaiton header link

---

lib/dpul_collections_web/live/search_live.ex
test/dpul_collections_web/live/search_live_test.exs

Add item counter to search results

---

README.md

Document solr credentials

---

.circleci/config.yml
config/deploy/staging.hcl
config/dev.exs
config/runtime.exs
config/test.exs
lib/dpul_collections/application.ex
lib/dpul_collections/indexing_pipeline/database_producer.ex
lib/dpul_collections/indexing_pipeline/figgy/hydration_consumer.ex
lib/dpul_collections/indexing_pipeline/figgy/indexing_consumer.ex
lib/dpul_collections/indexing_pipeline/figgy/transformation_consumer.ex
lib/dpul_collections/solr.ex
test/dpul_collections/indexing_pipeline/integration/figgy/hydration_integration_test.exs
test/dpul_collections/indexing_pipeline/integration/figgy/indexing_integration_test.exs
test/dpul_collections/indexing_pipeline/integration/figgy/transformation_integration_test.exs
test/dpul_collections/indexing_pipeline/integration/full_integration_test.exs
test/dpul_collections/solr_test.exs
test/dpul_collections_web/live/search_live_test.exs
test/support/figgy_test_support.ex
test/support/mock_figgy_hydration_producer.ex
test/support/mock_figgy_indexing_producer.ex
test/support/mock_figgy_transformation_producer.ex
test/support/solr_test_support.ex

advances #104 
depends on https://github.com/pulibrary/princeton_ansible/pull/5490 before it can be deployed.

Change solr configuration and code to allow writing to multiple indexes

---

.circleci/config.yml
config/deploy/staging.hcl
config/dev.exs

- **Remove extra collection from initial solr container**
- **Pass the config set env var**

Pass the config set env var

---

assets/css/app.css
lib/dpul_collections_web/live/home_live.ex
lib/dpul_collections_web/live/search_live.ex
test/dpul_collections_web/live/search_live_test.exs

WIP: fixes responsive buttons and forms

Fixes CSS for Homescreen and Search Results

---

lib/dpul_collections/indexing_pipeline/database_producer/cache_entry_marker.ex
lib/dpul_collections/indexing_pipeline/figgy/transformation_consumer.ex
test/dpul_collections/indexing_pipeline/database_producer/cache_entry_marker_test.exs

Work towards #183 - this completes the work for the TransformationConsumer.

Transform in handle_message, commit in handle_batch

---

lib/dpul_collections/indexing_pipeline/figgy/hydration_consumer.ex
test/dpul_collections/indexing_pipeline/figgy/hydration_consumer_test.exs

Hydrator should transform in handle_message, save in handle_batch

---

lib/dpul_collections_web/live/item_live.ex
test/dpul_collections_web/live/item_live_test.exs

Ensure URL encoded slugs don't cause redirect

---

config/deploy/staging.hcl
config/runtime.exs

It's now part of index_cache_collections
part of #104

Remove old cache_version configuration

---

lib/dpul_collections/indexing_pipeline/figgy/hydration_cache_entry.ex
test/dpul_collections/indexing_pipeline/integration/figgy/indexing_integration_test.exs
test/dpul_collections/indexing_pipeline/integration/full_integration_test.exs

Index IIIF service URLs

---

lib/dpul_collections_web/live/item_live.ex
lib/dpul_collections_web/live/search_live.ex

gray background image placeholders for search and item pages

---

lib/dpul_collections/indexing_pipeline/coherence.ex
lib/dpul_collections/solr.ex

Add and fix typespecs in solr.ex and coherence.ex

---

lib/dpul_collections_web/live/search_live.ex

Search shouldn't replace browser history on pagination.

---

lib/dpul_collections_web/live/search_live.ex
test/dpul_collections_web/live/search_live_test.exs

Closes #135 
- Apply button added for date filter
- Bumped font size for results
- Added h1 tag for page title
- Added thin border box

Fixes some styles and adds apply button

---

lib/dpul_collections_web/live/home_live.ex

Center and constrain width of the home page welcome text

---

config/deploy/staging.hcl
docs/admin/clean_index.md

Increment staging cache version and write_collection name

---

README.md

Document staging logs in README

---

solr/conf/schema.xml
solr/conf/solrconfig.xml

closes #237
I couldn't find a way to use wildcards here

Add stemmed title and description fields to query fields

---

docs/admin/clean_index.md
lib/dpul_collections/indexing_pipeline.ex
test/dpul_collections/indexing_pipeline_test.exs

Add and document a function to delete a cache version from the db

---

solr/conf/slug.js
test/dpul_collections/solr_test.exs
test/dpul_collections_web/live/item_live_test.exs

Closes #249 
- Fix RTL slug generation
- Remove ¡, ?, and ¿ from slugs

Improve slug generation

---

config/deploy/staging.hcl

I switched the alias; 3 is now the active cache version
closes #104

Finalize cache version 3

---

lib/dpul_collections/indexing_pipeline/figgy/hydration_cache_entry.ex
test/dpul_collections/indexing_pipeline/figgy/hydration_cache_entry_test.exs

So the record will still index
closes #213

Log date parse errors instead of erroring

---

lib/dpul_collections_web/live/search_live.ex
test/dpul_collections_web/live/search_live_test.exs

Conditionally render link or span in pagenation

---

lib/dpul_collections/indexing_pipeline/figgy/hydration_cache_entry.ex
test/dpul_collections/indexing_pipeline/figgy/hydration_cache_entry_test.exs

Handle file sets that do not have a service url

---

lib/dpul_collections/indexing_pipeline/figgy/hydration_cache_entry.ex
test/dpul_collections/indexing_pipeline/figgy/hydration_cache_entry_test.exs

Fixes issue introduced in https://github.com/pulibrary/dpul-collections/pull/255

Do not extract year in formatted_date

---

config/deploy/staging.hcl

Bump to cache version 5

---

config/config.exs
config/test.exs
lib/dpul_collections_web/live/item_live.ex
test/dpul_collections_web/live/item_live_test.exs

closes #257
- Add a primary-thumbnail class and fix large thumbnail test
- Add a pdf download link

Add a pdf download link

---

solr/conf/slug.js
test/dpul_collections/solr_test.exs

Remove trailing dashes from title slugs

---

solr/conf/slug.js
test/dpul_collections/solr_test.exs

Add ellipses character to list of removed punctuation

---

lib/dpul_collections_web/live/search_live.ex
priv/gettext/default.pot
priv/gettext/en/LC_MESSAGES/default.po
priv/gettext/es/LC_MESSAGES/default.po

closes #271
closes #273
closes #274

Update sort options and add translations

---

lib/dpul_collections_web/live/search_live.ex
test/dpul_collections_web/live/search_live_test.exs

Reset sort when changing query parameter

---

test/dpul_collections/index_metrics_tracker_test.exs

Remove unused alias

---

priv/gettext/default.pot
priv/gettext/en/LC_MESSAGES/default.po
priv/gettext/es/LC_MESSAGES/default.po

Follow-up to https://github.com/pulibrary/dpul-collections/pull/305

Remove unneeded translations

---

lib/dpul_collections_web/live/home_live.ex
test/dpul_collections_web/live/home_live_test.exs

Add link to browse page on home page

---

lib/dpul_collections_web/live/browse_live.ex

Browse Design Pass - Cards in 3 columns

---

lib/dpul_collections_web/live/browse_live.ex
test/dpul_collections_web/live/browse_live_test.exs

Set browse count to 50 documents

---

.circleci/config.yml
mix.exs
test/dpul_collections_web/features/locale_test.exs
test/dpul_collections_web/live/browse_live_test.exs

Fix tests in CI

---

lib/dpul_collections_web/live/browse_live.ex
test/dpul_collections_web/live/browse_live_test.exs

Request smaller images for non-primary thumbnails

---

lib/dpul_collections/indexing_pipeline/figgy/hydration_cache_entry.ex
lib/dpul_collections/solr.ex
lib/dpul_collections_web/live/home_live.ex
test/dpul_collections/indexing_pipeline/figgy/hydration_cache_entry_test.exs
test/dpul_collections/solr_test.exs
test/dpul_collections_web/live/home_live_test.exs
test/support/fixtures/figgy_test_fixtures.ex
test/support/solr_test_support.ex

Add recent items to home page

---

lib/dpul_collections_web/live/browse_live.ex

Browse Items Page Counts

---

lib/dpul_collections/indexing_pipeline/figgy/hydration_cache_entry.ex
lib/dpul_collections/item.ex
lib/dpul_collections_web/live/item_live.ex
test/dpul_collections/indexing_pipeline/figgy/hydration_cache_entry_test.exs
test/dpul_collections_web/live/home_live_test.exs
test/dpul_collections_web/live/item_live_test.exs
test/support/fixtures/figgy_test_fixtures.ex

Add more metadata

---

lib/dpul_collections/indexing_pipeline/figgy/hydration_cache_entry.ex
lib/dpul_collections/item.ex
test/dpul_collections/indexing_pipeline/figgy/hydration_cache_entry_test.exs
test/dpul_collections_web/live/item_live_test.exs
test/support/fixtures/figgy_test_fixtures.ex

Index rights statement

---

.circleci/config.yml
.tool-versions
README.md
mix.exs

Closes #386 
Simplifies #385 setup a little.

Add npm installation as part of mix setup.

---

lib/dpul_collections_web/live/browse_live.ex
test/dpul_collections_web/live/browse_live_test.exs

adjusted tests and increased resource count from 50 to 90

---

test/dpul_collections/indexing_pipeline/integration/full_integration_test.exs

Increase CI timeout for full integration test

---

lib/dpul_collections/item.ex
lib/dpul_collections_web/live/browse_live.ex
test/dpul_collections_web/live/browse_live_test.exs

There's a bunch of design work to do here, but this gets the basic "popping to the top" working.
Closes #315

Allow browse items to be pinned to the top.

---

README.md
architecture-decisions/0004-deleting-records.md
figgy-fixture-container/create-fixture-exports.sh
figgy-fixture-container/import-container-fixtures.sh
lib/dpul_collections/indexing_pipeline/database_producer.ex
lib/dpul_collections/indexing_pipeline/database_producer/cache_entry_marker.ex
lib/dpul_collections/indexing_pipeline/figgy/hydration_consumer.ex
test/dpul_collections/indexing_pipeline/figgy/hydration_cache_entry_test.exs
test/dpul_collections/indexing_pipeline/figgy/resource_test.exs
test/dpul_collections/indexing_pipeline/integration/full_integration_test.exs
test/support/fixtures/figgy_test_fixtures.ex

- **Update figgy fixtures**
- **Fix bug with DeletionMarker processing**
closes #412

Add new Figgy fixtures and update all other fixtures

---

config/deploy/staging.hcl
config/runtime.exs

closes #417
- Only run one index; we're getting db connection pool problems
- Increase pool size
- increase index ram

Work on db connection pool problems

---

lib/dpul_collections_web/indexing_pipeline/dashboard_page.ex
test/dpul_collections_web/indexing_pipeline/dashboard_page_test.exs

Add processor markers to indexing metrics dashboard

---

lib/dpul_collections/index_metrics_tracker.ex
lib/dpul_collections/indexing_pipeline/database_producer.ex
lib/dpul_collections/indexing_pipeline/index_metric.ex
lib/dpul_collections_web/indexing_pipeline/dashboard_page.ex
priv/repo/migrations/20250404213147_add_cache_version_to_index_metric.exs
test/dpul_collections/index_metrics_tracker_test.exs
test/dpul_collections_web/indexing_pipeline/dashboard_page_test.exs

Track cache versions for indexing metrics.

---

lib/dpul_collections_web/indexing_pipeline/dashboard_page.ex
test/dpul_collections_web/indexing_pipeline/dashboard_page_test.exs

Fix indexing metrics dashboard page when there are more than 3 markers

---

README.md
figgy-fixture-container/create-fixture-exports.sh

Adds fixtures to test font support for arabic and cyrillic characters

---

lib/dpul_collections_web/live/home_live.ex

Work towards #437 
On hover:
I considered making it like...get bigger, but it sounded hard so I didn't.

Add mosaic content area to front page

---

lib/dpul_collections/indexing_pipeline/figgy/resource.ex
test/dpul_collections/indexing_pipeline/figgy/hydration_consumer_test.exs
test/dpul_collections/indexing_pipeline/figgy/resource_test.exs
test/dpul_collections/indexing_pipeline/integration/full_integration_test.exs
test/support/fixtures/figgy_test_fixtures.ex

Filter out non-image file members

---

assets/css/app.css
lib/dpul_collections_web/components/layouts/app.html.heex
lib/dpul_collections_web/live/browse_live.ex
lib/dpul_collections_web/live/home_live.ex
lib/dpul_collections_web/live/search_live.ex
test/dpul_collections_web/live/home_live_test.exs

Update browse item card and adjust background colors

---

assets/css/app.css
lib/dpul_collections_web/live/item_live.ex
test/dpul_collections_web/live/item_live_test.exs

Style download and view buttons.

---

lib/dpul_collections_web/live/item_live.ex
priv/gettext/default.pot
priv/gettext/en/LC_MESSAGES/default.po
priv/gettext/es/LC_MESSAGES/default.po
test/dpul_collections_web/live/item_live_test.exs

Add page layout.

---

lib/dpul_collections/indexing_pipeline/figgy/hydration_cache_entry.ex
lib/dpul_collections/indexing_pipeline/figgy/resource.ex
test/dpul_collections/indexing_pipeline/figgy/hydration_cache_entry_test.exs
test/dpul_collections/indexing_pipeline/figgy/resource_test.exs
test/dpul_collections/indexing_pipeline/integration/figgy/hydration_integration_test.exs
test/dpul_collections/indexing_pipeline/integration/full_integration_test.exs

Closes #461 
- **Hydrate EphemeraProjects**
- **Hydrate EphemeraBoxes**
- **Recursively fetch ancestors**
- **Get parent EphemeraBox from ancestors map**
- **Ensure parent resource isn't fetched twice**

Index EpheremaProject title

---

assets/css/app.css
lib/dpul_collections/item.ex
lib/dpul_collections_web/live/item_live.ex
priv/gettext/default.pot
priv/gettext/en/LC_MESSAGES/default.po
priv/gettext/es/LC_MESSAGES/default.po
test/dpul_collections_web/live/item_live_test.exs

Add metadata table

---

assets/css/app.css
lib/dpul_collections_web/components/footer_component.ex
lib/dpul_collections_web/components/header_component.ex
lib/dpul_collections_web/components/search_bar_component.ex
lib/dpul_collections_web/live/home_live.ex

This proposal tries to reduce the number of different colors in the palette by making the secondary section a shade of the search bar. The goal is to maintain serenity, but have the color profile feel more consistent.
**Before**
**After**
Work towards #488

Color Iteration: Monochrome Search Bar

---

lib/dpul_collections/indexing_pipeline/figgy/hydration_cache_entry.ex
test/dpul_collections/indexing_pipeline/integration/full_integration_test.exs

Index pdf download link

---

assets/js/app.js
lib/dpul_collections_web/live/item_live.ex
test/dpul_collections_web/features/item_test.exs
test/dpul_collections_web/features/search_bar_test.exs

Closes #475
This was way harder than I expected.

Add a working share modal.

---

assets/css/app.css
lib/dpul_collections_web/live/home_live.ex

boost mosaic color; apply drop shadow to call to action; adjust language drop down text (it was light on light);

Incremental Home Page Design Refinements

---

lib/dpul_collections_web/components/browse_item.ex
lib/dpul_collections_web/live/browse_live.ex

Refines drop shadow colors for randomize button and browse items

---

.circleci/config.yml
.tool-versions
Dockerfile

Update elixir to 1.18.4

---

lib/dpul_collections_web/live/item_live.ex

Scroll back to top of page when metadata panel slides in

---

lib/dpul_collections_web/live/item_live.ex
test/dpul_collections_web/features/item_test.exs

Don't add metadata pane open / dismiss to browser history

---

lib/dpul_collections/solr.ex
lib/dpul_collections_web/components/browse_item.ex
lib/dpul_collections_web/live/home_live.ex
lib/dpul_collections_web/live/item_live.ex
priv/gettext/default.pot
priv/gettext/en/LC_MESSAGES/default.po
priv/gettext/es/LC_MESSAGES/default.po
solr/conf/solrconfig.xml
test/dpul_collections/solr_test.exs
test/dpul_collections_web/live/home_live_test.exs
test/dpul_collections_web/live/item_live_test.exs

Closes #394 
This adds recommended items for both items in the collection and items outside them.
It also makes a component for a "browse item row" that we use everywhere.

Add recommended items

---

lib/dpul_collections/solr.ex
lib/dpul_collections/solr/constants.ex
lib/dpul_collections_web/live/item_live.ex
lib/dpul_collections_web/live/search_live.ex
lib/dpul_collections_web/live/search_live/search_state.ex
test/dpul_collections/solr_test.exs
test/dpul_collections_web/live/helpers_test.exs
test/dpul_collections_web/live/item_live_metadata_test.exs
test/dpul_collections_web/live/item_live_viewer_test.exs
test/dpul_collections_web/live/search_live_test.exs

Closes #518 
- **Change facet to filter**
- **Fix warnings**

Change facet to filter

---

assets/css/app.css
lib/dpul_collections/solr/constants.ex
lib/dpul_collections_web/live/item_live.ex
priv/gettext/default.pot
test/dpul_collections_web/live/item_live_metadata_test.exs

Add filter links to metadata pane

---

assets/css/app.css
assets/css/clover.css

Add left margin to Clover thumbnail container

---

lib/dpul_collections_web/live/item_live.ex
test/support/solr_test_support.ex

Closes #563
- **Remove extra curly brace**
- **Only load SolrTestSupport when testing**

fix warnings

---

assets/js/dpulc_viewer.jsx

Reenables panning and zooming in Clover.

Enable Clover pan and zoom

---

lib/dpul_collections_web/components/header_component.ex
lib/dpul_collections_web/live/home_live.ex
test/dpul_collections_web/live/home_live_test.exs

Add photographs/posters/books links & make logo in header a link

---

lib/dpul_collections_web/components/header_component.ex

Fixes header icon and accessibility issues

---

lib/dpul_collections_web/live/item_live.ex
test/dpul_collections_web/live/item_live_test.exs

Closes #476 
This is deployed on staging right now.

Add Size functionality

---

lib/dpul_collections_web/components/browse_item.ex
lib/dpul_collections_web/components/search_bar_component.ex
lib/dpul_collections_web/live/item_live.ex
lib/dpul_collections_web/live/search_live.ex

Add automatic directionality for RTL fields.

---

lib/dpul_collections_web/components/layouts/root.html.heex
lib/dpul_collections_web/live/browse_live.ex
lib/dpul_collections_web/live/home_live.ex
lib/dpul_collections_web/live/item_live.ex
lib/dpul_collections_web/live/search_live.ex
test/dpul_collections_web/live/browse_live_test.exs
test/dpul_collections_web/live/home_live_test.exs
test/dpul_collections_web/live/item_live_test.exs
test/dpul_collections_web/live/search_live_test.exs

Closes #493
- **Add title to home page**
- **Add title to search results**
- **Add title to browse**
- **Add title to item page**

Custom html page titles

---

lib/dpul_collections_web/components/header_component.ex

We'll replace it when we have the translations
closes #607

Remove Portuguese from menu

---

lib/dpul_collections_web/live/browse_live.ex

Force scroll to top when randomize button is clicked

---

lib/dpul_collections_web/components/browse_item.ex
lib/dpul_collections_web/live/browse_live.ex
lib/dpul_collections_web/live/search_live.ex
test/dpul_collections_web/live/browse_live_test.exs
test/dpul_collections_web/live/home_live_test.exs
test/dpul_collections_web/live/item_live_test.exs
test/dpul_collections_web/live/search_live_test.exs

Make Cards Clickable

---

lib/dpul_collections_web/live/search_live.ex

Fixes search term wrapping

---

config/deploy/env/production.tpl
config/deploy/production.hcl

Add production config.

---

lib/dpul_collections/workers/cache_hero_images.ex
lib/dpul_collections/workers/cache_thumbnails.ex

Closes #339
Companion to: https://github.com/pulibrary/serverless-iiif/pull/21

Add x-cache-iiif-request header to thumbnail cache requests

---

config/deploy/env/production.tpl
config/deploy/env/staging.tpl
config/prod.exs

Use production environment for Honeybadger.

---

config/deploy/staging.hcl

Add bot protection to staging via consul tags.

---

config/deploy/production.hcl

There was a missing comma in #678

Fix production deploy.

---

priv/static/robots.txt

Block all robots.

---

lib/dpul_collections/indexing_pipeline.ex
lib/dpul_collections/indexing_pipeline/figgy/hydration_consumer.ex
test/dpul_collections/indexing_pipeline/figgy/hydration_consumer_test.exs
test/dpul_collections/indexing_pipeline/integration/figgy/hydration_integration_test.exs
test/dpul_collections_web/live/browse_live_test.exs

Closes #75 
- **Update EphemeraFolder when related EphemeraBox or EphemeraProject are updated**
- **Use real resource ids in hydration consumer test**
- **Cleanup warnings**

Update EphemeraFolder when related EphemeraBox or EphemeraProject are updated

---

config/config.exs
config/runtime.exs
lib/dpul_collections.ex
lib/dpul_collections_web.ex
lib/dpul_collections_web/components/analytics.ex
lib/dpul_collections_web/components/layouts/root.html.heex
test/dpul_collections/dpul_collections_test.exs
test/dpul_collections_web/live/home_live_test.exs

Use Google Tag manager in production.

---

config/runtime.exs

Fix env name for analytics.

---

lib/dpul_collections_web/live/search_live/search_state.ex
test/dpul_collections_web/live/search_live_test.exs

Use 50 as the default per_page.

---

lib/dpul_collections_web/components/core_components.ex

There was an error in the console on prod.

Fix bad hook.
