README.md
bin/deploy
config/deploy/staging.hcl

Refs #21
Not sure this is the best script, and the output includes the SSH banner and stuff, but it's pretty simple!
This does Slack notifications by updating Github, which will notify slack since we've registered deployment notifications in #figgy!

Add deploy script.

---

architecture-decisions/0001-document-architecture-decisions.md
architecture-decisions/0002-indexing.md

Add first draft of indexing ADR.

---

.gitignore
.lando.yml
README.md
figgy-fixture-container/Dockerfile
figgy-fixture-container/build-and-push.sh
figgy-fixture-container/create-fixture-exports.sh
figgy-fixture-container/import-container-fixtures.sh

The script `build-and-push.sh` in `figgy-fixture-container` will create a postgres 15 container with all the records for a single Ephemera Project.
This also sets up Lando to use that container and host it on port 5435.
Work towards #30

Build a fixture container of Figgy data for indexing.

---

architecture-decisions/0002-indexing.md

Note that this proposal -only- works because we've got an ACID-compliant database backing our log.

Proposal for opening up multiple consumers per log.

---

.github/workflows/build-docker-image.yml
.github/workflows/nightly-vuln-scanning.yml

CI should only do the build-docker-image container scan on merge and AFTER the new image is built, so it's scanning the new version.
Before this PR, the nightly-vuln-scanning was handling this happening on merge, which was making the github actions on merge fail.

Fix container scanning on merge.

---

test/dpul_collections/indexing_pipeline/figgy_producer_test.exs

Use pattern matching to set initial_state variable

---

test/dpul_collections/indexing_pipeline/integration/figgy_hydrator_integration_test.exs
test/support/figgy_test_support.ex

This adds an integration test that does everything by kicking off all resources and waiting for the last one to show up in the database. It spawns a process with `Task.async` so we can set a timeout, so if it's too slow it crashes.
This test takes something like three seconds, so either we have to be okay with that for now, or find a way to be happy with unit tests for this filtering functionality somehow.

Add an integration test that hydrates the full data set.

---

config/config.exs
config/test.exs
lib/dpul_collections/indexing_pipeline/figgy/hydration_producer.ex
test/dpul_collections/indexing_pipeline/figgy/hydration_producer_test.exs

This adds polling to the Figgy hydration producer.
It updates every minute as per the ticket, but is configurable so that we can change it in test so that it actually triggers and we get test coverage.
Closes #74

Figgy Hydrator Polling

---

lib/dpul_collections/indexing_pipeline/figgy/hydration_consumer.ex
test/dpul_collections/indexing_pipeline/figgy/hydration_consumer_test.exs

Only open and complete resources

---

lib/dpul_collections/indexing_pipeline/figgy/hydration_producer.ex
lib/dpul_collections/indexing_pipeline/figgy/transformation_producer.ex
test/dpul_collections/indexing_pipeline/figgy/hydration_producer_test.exs
test/dpul_collections/indexing_pipeline/figgy/transformation_producer_test.exs
test/dpul_collections/indexing_pipeline/integration/figgy/hydration_integration_test.exs
test/dpul_collections/indexing_pipeline/integration/figgy/transformation_integration_test.exs
test/dpul_collections/indexing_pipeline/integration/full_integration_test.exs
test/support/mock_figgy_transformation_producer.ex

Use "figgy_hydrator" instead of "hydrator" for processor marker.
Use transformation_* instead of transformer_* and hydration_* instead of hydrator_*.

small refactors for language consistency

---

lib/dpul_collections/indexing_pipeline/figgy/transformation_consumer.ex
solr/config/schema.xml
solr/config/solrconfig.xml
test/dpul_collections/indexing_pipeline/integration/full_integration_test.exs
test/support/figgy_test_support.ex

This uses Solr's language detection features to generate a description field for every language it could be, so we can hopefully improve searching for that field, given that we know it's going to be in multiple languages.
I do not know how we'll actually enable search for all these languages, but at least this would get us them separated out.
Solr language detection: https://solr.apache.org/guide/7_2/detecting-languages-during-indexing.html
Closes #111

Descriptions w/ Language Detection

---

lib/dpul_collections/indexing_pipeline/figgy/hydration_cache_entry.ex
solr/conf/schema.xml
solr/conf/solrconfig.xml
test/dpul_collections/indexing_pipeline/integration/figgy/transformation_integration_test.exs
test/dpul_collections/indexing_pipeline/integration/full_integration_test.exs
test/dpul_collections_web/live/search_live_test.exs
test/support/fixtures/figgy_test_fixtures.ex

Notes:
1. Language detection doesn't work on copied fields, so we need to index title_txtm, then copy to title_ss.
2. Language detection on short strings is a little wonky, but that's probably fine. For instance, it really thinks 'Ali Bagheri' is German.
Closes #142

Title language detection & Tokenized Search

---

bin/console
config/deploy/staging.hcl
config/runtime.exs

Logs consulted via the nomad UI said to either do this or set `url: host:` for the given environment.
closes #147

Add check_origin

---

architecture-decisions/0003-one-indexer.md
config/deploy/staging.hcl
config/runtime.exs
lib/dpul_collections/application.ex

In Production this will run an indexer only if INDEXER is set to true in the environment. The nomad definition has its own group for that, so we can say to only have one with a lot more resources.
Closes #120 
Closes #119

Run one indexer

---

lib/dpul_collections/indexing_pipeline.ex

We found out that asking for an exact updated_at date was doing a full index scan of all of Figgy, timing out queries. This should be equivalent, and performs better.
Closes #165

Speed up Figgy Resources query.

---

.circleci/config.yml
.gitignore
.lando.yml
bin/setup_solr.sh
config/dev.exs
config/test.exs

- **Update lando to use solr cloud**
- **Replicate new solr test setup in ci**
advances #104 
Implications of this PR are that in development and test solr instances, there is now basic auth in place. I added a credential "user:pass" to make logging in slightly simpler than it is in the container's default settings.

Use solr cloud in local tests, add additional collection and alias

---

config/deploy/staging.hcl
rel/env.sh.eex
rel/remote.vm.args.eex
rel/vm.args.eex

This does the following:
1. Disables EPMD (Erlang Port Mapper Daemon)
2. Makes all distribution traffic go through a known port (6789).
3. Forwards that port for each web instance.
4. Uses the DNS server on the host so it can run consul queries.
5. Uses a consul DNS query to get all hosts running DPUL-C.
6. Configures dns_cluster to query those hosts.
Companion PR: https://github.com/pulibrary/princeton_ansible/pull/5424
Closes #118

Cluster DPUL-Collections nodes w/ DNS

---

config/deploy/staging.hcl
config/runtime.exs

I would have broken this out into other functions but you can't define a function inside the runtime because it's not a module.
follow up to #188 which fails to deploy due to a json parsing error; I couldn't find an effective way to pass those escaped quotes through hcl into the env var.

104 followup

---

.github/workflows/build-docker-image.yml
.github/workflows/nightly-vuln-scanning.yml

Workaround for https://github.com/aquasecurity/trivy-action/issues/389

Use Amazon for Trivy's DB.

---

bin/console

This searches `nomad job allocs` for the correct allocation ID for a given task name, then executes the command on that allocation.
Now `JOBTASK=indexer ./bin/console staging repl` will connect to the indexer repl.
Closes #193

Update bin/console to be able to connect to indexer reliably.

---

lib/dpul_collections/indexing_pipeline.ex
lib/dpul_collections/indexing_pipeline/figgy/hydration_cache_entry.ex
lib/dpul_collections/indexing_pipeline/figgy/hydration_consumer.ex
lib/dpul_collections/indexing_pipeline/figgy/resource.ex
priv/repo/migrations/20241107191219_add_related_data_to_hydration_cache_entry.exs
test/dpul_collections/indexing_pipeline/integration/figgy/hydration_integration_test.exs
test/support/figgy_test_support.ex
test/support/fixtures/figgy_test_fixtures.ex

- **Get a test written that hydrates an EphemeraFolder.**
- **Add related_data json field.**
- **Start storing some amount of related_data.**
- **Initial implementation done.**
Closes #73

Add related data to hydration cache

---

lib/dpul_collections/item.ex
lib/dpul_collections_web/live/item_live.ex
test/dpul_collections_web/live/item_live_test.exs

* Adds description
- We said we'd add ellipses, but the CSS for this turned out to be pretty impossible - CSS ellipses is mostly for single-lines, and requires an absolute width.
- This makes two divs for description so that in mobile it's below the image, but in desktop it's below the title. It's not the cleanest thing, but it works pretty effectively.
* Increases header sizes for the show page.
Closes #124
Increased headers:
Mobile description after thumbnail:
Long description:

Updated show page.

---

docs/admin/clean_index.md
lib/dpul_collections/indexing_pipeline.ex
lib/dpul_collections/indexing_pipeline/coherence.ex
test/dpul_collections/indexing_pipeline/coherence_test.exs

Compare indexing progress using the figgy timestamp

---

lib/dpul_collections/indexing_pipeline/figgy/hydration_cache_entry.ex
lib/dpul_collections/solr.ex
test/dpul_collections/indexing_pipeline/coherence_test.exs
test/dpul_collections/indexing_pipeline/figgy/hydration_cache_entry_test.exs
test/dpul_collections/indexing_pipeline/integration/figgy/indexing_integration_test.exs
test/dpul_collections/indexing_pipeline_test.exs
test/dpul_collections/solr_test.exs

Work towards #268
- Index documents one at a time after batch Solr update returns an error
- Assign default value when title is missing
- Resolves a couple of test warnings.
Current counts:
Figgy: 56172
Hydration Cache: 56106
Transformation Cache: 56106
Solr Records: 56106

Handle transformation and solr indexing errors

---

solr/conf/schema.xml
test/dpul_collections_web/live/search_live_test.exs

companion PR: pulibrary/pul_solr#445
This will probably require a reindex (via `DpulCollections.IndexingPipeline.Figgy.IndexingConsumer.start_over!(n)`)
advances #272

Sort nil dates last in both directions

---

test/dpul_collections_web/live/search_live_test.exs

So that you can index extra records if needed and have them cleaned up
before the next test run
closes #280

Set up search tests individually

---

README.md

And move "connect to staging" documentation above other things that rely
on it

Add documentation to get current active cache version

---

lib/dpul_collections_web/controllers/error_html.ex
lib/dpul_collections_web/controllers/error_html/404.html.heex
lib/dpul_collections_web/live/item_live.ex
lib/dpul_collections_web/live/item_live/not_found_error.ex
priv/gettext/default.pot
priv/gettext/en/LC_MESSAGES/default.po
priv/gettext/es/LC_MESSAGES/default.po
test/dpul_collections_web/controllers/error_html_test.exs
test/dpul_collections_web/live/item_live_test.exs
test/dpul_collections_web/live/search_live_test.exs

The liveview throws an error which causes the regular view to render.
screenshot, showing 404 status in network pane:
closes #207

Render 404 with the correct status when item is not found

---

config/deploy/log-shipping.hcl

It was failing because podman needs a full address, not a shortname.
Closes #296

Use full docker.io address for promtail.

---

config/dev.exs
config/prod.exs
config/runtime.exs
config/test.exs
lib/dpul_collections/application.ex

closes https://github.com/pulibrary/dpul-collections/issues/299
Adjusts to use best practice of not referring directly to the
environment to determine code path

Use a configured function to determine whether to start indexing

---

README.md
config/runtime.exs

Closes #301
We might want to set this up in a docker-compose at some point..

Add working example for setting up local prod docker image.

---

lib/dpul_collections/indexing_pipeline/figgy/hydration_cache_entry.ex
lib/dpul_collections/item.ex
lib/dpul_collections/solr.ex
lib/dpul_collections_web/live/item_live.ex
lib/dpul_collections_web/live/search_live.ex
test/dpul_collections/indexing_pipeline/figgy/hydration_cache_entry_test.exs
test/dpul_collections/indexing_pipeline/integration/full_integration_test.exs
test/dpul_collections_web/live/item_live_test.exs
test/dpul_collections_web/live/search_live_test.exs
test/support/solr_test_support.ex

Closes #159 
- **Extract thumbnail url**
- **Render large show page thumbnail using thumbnail service url**
- **Handle thumbnail ids that do not correspond to FileSets**
- **Render primary thumbnail first and limit total thumbnails**

Index primary thumbnail id

---

lib/dpul_collections/indexing_pipeline.ex
lib/dpul_collections/indexing_pipeline/figgy/resource.ex
test/dpul_collections/indexing_pipeline_test.exs

Get all members at once, rather than one at a time from the db

---

.circleci/config.yml

that doesn't run all the containers?

Can we have different executor for the format task

---

lib/dpul_collections_web/live/browse_live.ex

Just a spike to see what it'd look like.
closes #314 
Comparing results:
This PR:
Originally:

Browse with four pics next to it.

---

assets/js/app.js
lib/dpul_collections_web/components/header_component.ex
lib/plug/locale_plug.ex
test/dpul_collections_web/features/locale_test.exs

Instead of relying on a locale parameter to set language, set enable the language dropdown to set the locale cookie and reload. Avoids removing parameters from url when changing language.
Closes #265

Improve language selection by setting cookie with current locale

---

lib/dpul_collections/indexing_pipeline/figgy/hydration_consumer.ex
lib/dpul_collections/indexing_pipeline/figgy/resource.ex
test/dpul_collections/indexing_pipeline/figgy/hydration_consumer_test.exs

Delete records when visiblity or state change

---

lib/dpul_collections_web/live/browse_live.ex

Question before merging:
I noticed that I could modify the URL in the following way: "/browse?r=1000abc" and results would still be generated (no button press involved).
Depending on how result sets are currently stored on the server-side, I was wondering if allowing for this functionality enables a malicious user to consume lots of memory in the event they repeatedly automatically generate their own queries. (e.g.) "/browse?r=1000abcd", "/browse?r=1000abcde", "/browse?r=1000abcdee" ...
If this is the case, should a ticket for cleaning the input and ensuring only numbers between the specified range can actually be queried be made?

updates random values from 3000 to 1000000 for the item browse

---

lib/dpul_collections/indexing_pipeline/figgy/resource.ex
test/dpul_collections/indexing_pipeline/figgy/resource_test.exs

Filter related resource ids with empty strings

---

.circleci/config.yml

Given that the test times out intermittently it may be helpful to see
how long it takes over a few runs
refs #392

Output more data for each test result, including runtime

---

lib/dpul_collections_web/components/layouts/app.html.heex
lib/dpul_collections_web/components/search_bar_component.ex
lib/dpul_collections_web/live/home_live.ex
lib/dpul_collections_web/live/search_live.ex
test/dpul_collections_web/features/search_bar_test.exs
test/dpul_collections_web/live/search_live_test.exs

closes #230
Home Page with new Search Bar component:
Also replaces the search input on the results page with a header showing the given search term. This seemed in line with the decision made in https://github.com/pulibrary/dpul-collections/issues/264#issuecomment-2634578111 to prioritize the "new search" use case over the "adjust that search I just did" use case. Results page after this PR:

Add Search Bar as a component

---

lib/dpul_collections/indexing_pipeline.ex
lib/dpul_collections/indexing_pipeline/figgy/hydration_consumer.ex
lib/dpul_collections/indexing_pipeline/figgy/resource.ex
test/dpul_collections/indexing_pipeline/figgy/hydration_consumer_test.exs
test/dpul_collections/indexing_pipeline_test.exs

Closes #420
I'm not sure if this is my favorite implementation - sometimes there's
metadata, and sometimes there's not, and it keys off of that knowledge
to know if it should query for more, and I don't totally love that. It does work though!

Hydration Consumer should only use small messages while possible.

---

lib/dpul_collections/solr.ex
lib/dpul_collections/solr/constants.ex
lib/dpul_collections_web/live/search_live.ex
priv/gettext/default.pot
priv/gettext/en/LC_MESSAGES/default.po
priv/gettext/es/LC_MESSAGES/default.po
test/dpul_collections_web/live/search_live_test.exs
test/support/solr_test_support.ex

This also does some refactoring of sort_by, so to add new things we just update `Solr.Constants`. `https://hexdocs.pm/elixir/module-attributes.html#as-compile-time-constants` said that's pretty common. Maybe it should be elsewhere though? I dunno.
The macro business is a little complicated - basically we have to have module attributes to use them in function guards, but you can't call attributes from another module, so we have to compile-time define them in places we want to use those constants. To do that we can do `use` and `using`, effectively working as a module include from Ruby (hmmm, maybe that's bad..), to make it available to the compiler.
We also have to call Gettext's macro directly, because if I `use Gettext` in that `__using__` then it complains for modules that already `use …

Add recently added to sort_by

---

config/deploy/prometheus.hcl

I needed metrics on the NFS mount to watch for latency problems, given CheckMK alerts that it's stalling.
Refs pulibrary/figgy#6671
This also adds a cool new Nomad dashboard:
https://grafana-nomad.lib.princeton.edu/d/masiNomadCluster/cluster-overview?from=now-15m&to=now&var-datacenter=dc1&var-host=$__all&refresh=1m

[Prometheus] Add Figgy Staging & Nomad Metrics to Prometheus

---

lib/dpul_collections/indexing_pipeline/figgy/hydration_consumer.ex
lib/dpul_collections/indexing_pipeline/figgy/indexing_consumer.ex
lib/dpul_collections/indexing_pipeline/figgy/transformation_consumer.ex

These were happening because this line: https://github.com/akoutmos/prom_ex/blob/master/lib/prom_ex/plugins/broadway.ex#L146 is expecting that processor concurrency is set. We were just accepting the default. This explicitly puts in the default, which is System.schedulers_online()*2, according to https://hexdocs.pm/broadway/Broadway.html#start_link/2-processors-options
Closes #447

Stop telemetry message crashing.

---

lib/dpul_collections_web/live/home_live.ex

I wanted to see what it would look like if we had an intro box over our mosaic like https://pdimagearchive.org/.
I'd have to do a lot to get this to display right in Mobile, so before I do that I wanted some feedback on if this was interesting to us at all.
The text is flexible, obviously.

Add intro context in front of the mosaic

---

test/dpul_collections_web/features/locale_test.exs

We don't have tests set up to handle async solr access. This is what was
causing `mix test` failures locally.
Closes #467

Don't run locale test asynchronously.

---

assets/css/app.css
lib/dpul_collections_web/components/browse_item.ex
lib/dpul_collections_web/components/search_bar_component.ex
lib/dpul_collections_web/live/home_live.ex
lib/dpul_collections_web/live/item_live.ex

Oh, this also uses the princeton black as the brand color, and integrates that color into the site via the text color.
refs #488
After

Lighten the colors on the home page in particular, use sage as primary

---

assets/css/app.css
lib/dpul_collections/item.ex
lib/dpul_collections_web/live/item_live.ex
priv/gettext/default.pot
priv/gettext/en/LC_MESSAGES/default.po
priv/gettext/es/LC_MESSAGES/default.po
test/dpul_collections_web/live/item_live_test.exs

Closes #287
This also fixes the semantics for links/buttons in the Item page by
creating links when there's an `href`, and buttons otherwise.

Display PDF Button

---

assets/css/app.css
lib/dpul_collections_web/components/browse_item.ex

I thought a green secondary might tie the color scheme together more, and it turned out the color used on the search bar was the right contrast against the taupe. But on the item page it was hard to distinguish it from the primary color so I bumped that a bit darker.

Try a green secondary shade -- required bumping primary a bit darker

---

lib/dpul_collections/solr.ex
lib/dpul_collections/solr/constants.ex
lib/dpul_collections_web/live/browse_live.ex
lib/dpul_collections_web/live/helpers.ex
lib/dpul_collections_web/live/item_live.ex
lib/dpul_collections_web/live/search_live.ex
lib/dpul_collections_web/live/search_live/search_state.ex
test/dpul_collections_web/live/helpers_test.exs
test/dpul_collections_web/live/search_live_test.exs
test/support/solr_test_support.ex

Closes #485 
This refactors existing facets to be much more configurable (in `Constants.ex`) and makes faceting work in a much more general way, to make it easier to add simple facets later.
It also converts faceting to use the `fq` parameter (which Solr can cache, and which is a little easier to combine separate from the query param)

Genre Facet

---

lib/dpul_collections_web/live/item_live.ex

Closes #529
Apparently phx-remove fires even when navigating.

Fix links working when in Item panes.

---

assets/js/app.js
assets/js/dpulc_viewer.jsx
lib/dpul_collections_web/components/layouts/root.html.heex
lib/dpul_collections_web/live/item_live.ex

I want to do more, like disable mouse scroll but keep pan, but it looks
like to do that we either need 
https://github.com/openseadragon/openseadragon/issues/2151 or add a
placeholder canvas to our manifests which requires IIIF 3 manifests. 
Closes #532 
Closes #531

Make viewer take full space, don't capture mouse events

---

lib/dpul_collections_web/live/item_live.ex
test/dpul_collections_web/live/item_live_test.exs

Closes #545 
The only downside to these are that the window jumps around - we should find a way to get the height/width of these ahead of time so we can render the correct sized box.

Try item page thumbnails that maintain aspect ratio.

---

README.md
lib/dpul_collections_web/live/item_live.ex
test/dpul_collections_web/live/item_live_test.exs

- Reorganize item_live_test
- Move ids and classes to more localized places
- Wrap primary thumbnail in link, ensure it opens to the thumbnail
- Add link to view all images, only show it if there are > 12
closes #575
Note to reviewer: You may want to review commits 1 at a time, the first 2 are refactors and the second 2 implement the ticket requirements.

Add viewer links on item page

---

assets/css/app.css
lib/dpul_collections_web/components/search_bar_component.ex
lib/dpul_collections_web/live/home_live.ex
priv/gettext/default.pot
priv/gettext/en/LC_MESSAGES/default.po
priv/gettext/es/LC_MESSAGES/default.po
test/dpul_collections_web/features/locale_test.exs
test/dpul_collections_web/live/home_live_test.exs

Also desaturates the mosaic images a bit, to forward the call to action
Also changes "browse" language to "explore" and removes "all items"
closes #489
drafted pending translations but posting for consideration

Add primary color background and corner cut decoration to call to action

---

lib/dpul_collections_web/live/home_live.ex

- **Prevent mosaic images from being tabbable.**
- **Set image as presentation.**
I'm not 100% sure about the accessibility of this, but it's what the automated tests let through...
Closes #605

Mosaic images should not be tabbable and marked as for presentation.

---

bin/deploy
config/deploy/env/staging.tpl
config/deploy/staging.hcl

Refactor staging.hcl to reference a file for common environment variables, rather than repeating the same stanza 3 times and using hcl vars.

Use a common env file for staging web and indexer

---

lib/dpul_collections_web/live/search_live.ex
test/dpul_collections_web/live/search_live_test.exs

refactor page_link_or_span out of its own module, close to its caller
closes #642
screenshot:

Style paginator current page

---

assets/css/app.css
lib/dpul_collections_web/components/core_components.ex
lib/dpul_collections_web/live/item_live.ex

- adjust left-arrow-box and right-arrow-box for consistent arrow size
and styling
- fix erroneous tailwind padding syntax on primary button
- ensure metadata button text and icon stay together, while allowing for
wrapping when necessary (actually because of making it smaller on smallest screens it doesn't really wrap anymore)
- make the font and icon size smaller for the smallest screen sizes
closes #643 
screenshot, average case:
screenshot, smallest width case:

Align icon and text in right-arrow metadata button

---

assets/css/app.css
lib/dpul_collections_web/components/header_component.ex
lib/dpul_collections_web/components/search_bar_component.ex

closes #645
- Move little pul logo into link, giving correct alignment
- Add min height to search bar browse link
- Increase spacing between site title and language dropdown on mobile
- Fix browse item row width on smallest mobile
smallest size, before: 
smallest size, after:
second-smallest size, before:
second-smallest size, after:

Adjust mobile header styles

---

lib/dpul_collections_web/components/browse_item.ex
test/dpul_collections_web/live/browse_live_test.exs

Truncate titles on browse cards to 70 characters

---

config/test.exs
lib/dpul_collections/indexing_pipeline/figgy/hydration_cache_entry.ex
test/dpul_collections/indexing_pipeline/figgy/hydration_cache_entry_test.exs

advances #371
At some point we'll have to also check for content warnings in source metadata but that will be part of bringing in non-ephemera resources.

Index content warnings

---

lib/dpul_collections/indexing_pipeline/database_producer.ex
lib/dpul_collections/indexing_pipeline/figgy/hydration_consumer.ex
lib/dpul_collections/indexing_pipeline/figgy/hydration_producer_source.ex
lib/dpul_collections/indexing_pipeline/figgy/indexing_consumer.ex
lib/dpul_collections/indexing_pipeline/figgy/indexing_producer_source.ex
lib/dpul_collections/indexing_pipeline/figgy/transformation_consumer.ex
lib/dpul_collections/indexing_pipeline/figgy/transformation_producer_source.ex
test/support/figgy_test_support.ex

This should result in a ton less chatter and load against the database - it'll only poll every minute, and most of the time that'll be empty (except for the Hydrator, which polls Figgy.)
Also, this speeds up the tests by so much. I'm not sure why - probably a side effect of the pooled transaction database only allowing one query at a time. It brings the test suite from 118 seconds in https://github.com/pulibrary/dpul-collections/pull/718 to 68 seconds.
Work towards #679

Use telemetry to notify stages to poll for changes.

---

assets/js/dpulc_viewer.jsx
lib/dpul_collections_web/live/item_live.ex

Some iteration on #689 
This puts thumbnails on the left side of the screen as long as you're above Tailwind's sm breakpoint.

Thumbnail on left

---

assets/js/hooks.js
lib/dpul_collections_web/components/core_components.ex
lib/dpul_collections_web/content_warnings.ex
lib/dpul_collections_web/live/item_live.ex
test/dpul_collections_web/features/item_test.exs

This makes the Share and Content Warning modals use the same code and hooks, which improves the accessibility of the Share modal by making background content inert.
Work towards #490

Create a Modal CoreComponent

---

lib/dpul_collections/indexing_pipeline/database_producer.ex
lib/dpul_collections/indexing_pipeline/figgy/hydration_consumer.ex
lib/dpul_collections/indexing_pipeline/figgy/hydration_producer_source.ex
test/dpul_collections/indexing_pipeline/figgy/hydration_consumer_test.exs
test/dpul_collections/indexing_pipeline/integration/full_integration_test.exs

I couldn't help myself looking at the Broadway dashboard and seeing resources get locked up in the batcher processor, the memory max out, and all the time get locked up querying for resources. I wanted to see if I could try this small improvement and see if it makes things better.
This prevents concurrent processors from waiting for records by always fetching at least 500 records in the producer, and prevents memory bloat by persisting records in `handle_message` to prevent sending large combined records to the batcher.

Trying a couple small hydrator performance improvements

---

lib/dpul_collections/indexing_pipeline/figgy/transformation_consumer.ex
lib/dpul_collections/indexing_pipeline/figgy/transformation_producer_source.ex
test/dpul_collections/indexing_pipeline/database_producer_test.exs

Buffers 500 records at a time and doesn't pass them through to a batcher.
This brings transformation time from 16 minutes to 7.5.
Similar to #773

Improve transformation consumer the same way we did HydrationConsumer.

---

lib/dpul_collections/solr.ex
lib/dpul_collections/solr/constants.ex
lib/dpul_collections_web/live/search_live.ex
test/dpul_collections/indexing_pipeline/coherence_test.exs
test/dpul_collections/indexing_pipeline/integration/figgy/hydration_integration_test.exs
test/dpul_collections/indexing_pipeline/integration/figgy/indexing_integration_test.exs
test/dpul_collections/indexing_pipeline/integration/full_integration_test.exs
test/dpul_collections/solr/management_test.exs
test/dpul_collections/solr_test.exs
test/dpul_collections/workers/cache_mosaic_images_test.exs
test/dpul_collections_web/controllers/iiif_content_state_controller_test.exs
test/dpul_collections_web/features/browse_test.exs
test/dpul_collections_web/features/content_warnings_test.exs
test/dpul_collections_web/features/home_test.exs
test/dpul_collections_web/features/item_test.exs
test/dpul_collections_web/features/locale_test.exs
test/dpul_collections_web/features/search_bar_test.exs
test/dpul_collections_web/features/search_test.exs
test/dpul_collections_web/live/browse_live_test.exs
test/dpul_collections_web/live/home_live_test.exs
test/dpul_collections_web/live/item_live_metadata_test.exs
test/dpul_collections_web/live/item_live_test.exs
test/dpul_collections_web/live/item_live_viewer_test.exs
test/dpul_collections_web/live/search_live_test.exs
test/support/conn_case.ex
test/support/data_case.ex
test/support/figgy_test_support.ex

- **Remove async: true from ContentStateController, it uses Solr.**
- **Projects should not appear in related items.**
- **Telemetry should be disconnected when the tests end.**
- **Use AckTracker for Hydration Integration Test.**
- **Don't depend on order for blank query search tests.**
- **Consistently clear Solr before every test module, and after each test.**
Closes #815 
This is draft until I've run the test suite 60 times without failure: `mix test --repeat-until-failure 60 --max-failures 1`

Fix flaky tests

---

test/dpul_collections_web/live/search_live_test.exs
test/support/solr_test_support.ex

Since not all the project metadata is in the item document this'll make sure Axe tests the new tagline feature.
It looks like a lot of changes but most of it is indenting - the key thing is it just adds an `ephemera_project_id_s` to the mock documents that feature tests use, and makes sure that the appropriate project is also indexed.

Add project to mock documents so color contrast is tested.
